version: "3.8"

services:
  # 1. DATABASE (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: interior_shop_microservices_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # Cổng 5433 để máy ngoài kết nối (nếu thích)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  # 2. REDIS
  redis:
    image: redis:alpine
    container_name: interior_shop_microservices_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  # 3. PGADMIN (Giao diện Web)
  pgadmin:
    image: dpage/pgadmin4
    container_name: interior_shop_microservices_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Tài khoản đăng nhập web
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Vào bằng localhost:5050
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
